<?php
return [
    [
        'id' => 1,
        'fullname' => 'محمد بیرجندی',
        'username' => 'mohammad',
        'email' => 'mohammad@gmial.com',
        'isAdmin' => 1,
        'status' => 1,
        'password' => '$2y$13$gsqQfm4cgiiCt8TmS.bcjeZWfPxz5sTX97c4T7HQBu4fCxau67rt6',
        'accessToken' => 'APH8YYTxcMqMUDyOwnzXu1qX9A9T-SIq',
        'authKey' => '-HNPdQatwYRRRKPQrTcFKcGIzm-WALqT',
        'created_at' => "2021-08-23 12:42:20",
    ],
    [
        'id' => 2,
        'fullname' => 'علی مشهدی',
        'username' => 'ali88',
        'email' => 'ali88@gmial.com',
        'isAdmin' => 1,
        'status' => 1,
        'password' => '$2y$13$gsqQfm4cgiiCt8TmS.bcjeZWfPxz5sTX97c4T7HQBu4fCxau67rt6',
        'accessToken' => 'DFJ8YYTxcMqMUDyOwnzXu1qX9A9T-SIq',
        'authKey' => '-HNDFWatwYRRRKPQrTcFKcGIzm-WALqT',
        'created_at' => "2021-08-23 12:42:10",
    ],
    [
        'id' => 3,
        'fullname' => 'مریم کرمانی',
        'username' => 'maryam',
        'email' => 'maryam@gmial.com',
        'isAdmin' => 1,
        'status' => 1,
        'password' => '$2y$13$gsqQfm4cgiiCt8TmS.bcjeZWfPxz5sTX97c4T7HQBu4fCxau67rt6',
        'accessToken' => 'ER8YRTxcMqMUDyOwnzXu1qX9A9T-SIq',
        'authKey' => '-ERPdWatwERRRKPQrTcFKcGIzm-WALqT',
        'created_at' => "2021-08-23 12:42:00",
    ],
];